# Generated by Django 4.2 on 2023-04-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='status',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='list',
            new_name='todo_list',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='description',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='content',
            field=models.CharField(default='Default content', max_length=255),
        ),
    ]
